version : "3.8"
services:
  client:
    build:
      context: app
      dockerfile: Dockerfile.dev
    environment:
      API_URL: http://localhost:8000/api
    ports:
      - 3000:3000
    volumes:
      - /app/node_modules
      - ./app:/app
    depends_on:
      - api
      - postgres

  api:
    build:
      context: ./api
    depends_on:
      - postgres
    env_file:
      - server.env
    ports:
      - 8000:8000
    volumes:
      - /app/node_modules
      - ./api:/app
  postgres:
    image: postgres:13
    hostname: postgres
    container_name: postgres
    restart: always
    ports:
      - 5432:5432
    env_file:
      - postgres.env
    volumes:
        - database-data:/var/lib/postgresql/data/ # persist data even if container shuts down
volumes:
  database-data: # named volumes can be managed easier using docker-compose