version : "3.8"
services:
  client:
    build:
      context: app
      dockerfile: Dockerfile.dev
    ports:
      - 3000:3000
    volumes:
      - /app/node_modules
      - ./app:/app
    depends_on:
      - server
      - postgres

  server:
    build:
      context: server
    depends_on:
      - postgres
    env_file:
      - server.env

  postgres:
    image: postgres:13
    hostname: postgres
    container_name: postgres
    restart: always
    ports:
      - 5432:5432
    env_file:
      - postgres.env
    volumes:
        - database-data:/var/lib/postgresql/data/ # persist data even if container shuts down
volumes:
  database-data: # named volumes can be managed easier using docker-compose