version: 2.1

orbs:
  node: circleci/node@4.1.0

jobs:
  app-lint:
    executor:
      name: node/default
      tag: 'lts'
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: yarn
          app-dir: app
      - run:
          command: cd app && yarn lint
          name: Run linter on app
      - persist_to_workspace:
          root: ~/project
          paths:
            - app/node_modules
  app-build:
    executor:
      name: node/default
      tag: 'lts'
    steps:
      - checkout
      - attach_workspace:
          at: ~/project
      - run:
          name: Build
          command: cd app && yarn build
      - persist_to_workspace:
          root: ~/project
          paths:
            - app/dist
  build-archives:
    executor:
      name: node/default
      tag: 'lts'
    steps:
      - checkout
      - attach_workspace:
          at: ~/project
      - run:
          name: Create archive
          command: tar -czf archive.tar.gz app/dist
      - store_artifacts:
          path: archive.tar.gz
          destination: /home/circleci/project/archive.tar.gz
workflows:
  build:
    jobs:
      - app-lint
      - app-build:
          requires:
            - app-lint
      - build-archives:
          requires:
            - app-build