version: 2.1

orbs:
  node: circleci/node@4.1.0

jobs:
  app-lint:
    executor:
      name: node/default
      tag: 'lts'
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: yarn
          app-dir: /app
      - run:
          command: cd app && yarn lint
          name: Run linter on app

workflows:
  build:
    jobs:
      - app-lint

