# base image
FROM node:14.14.0-alpine

WORKDIR /app

  # copy file FROM (relative to the current build context) your local TO CONTAINER path
COPY ./package.json ./
RUN npm install
COPY ./ ./

CMD ["npm","run","start"]
