default_sites: |
    server {
            listen 80;
            listen [::]:80;

            root /var/www/test-mv.com/html;
            index index.html index.htm;

            server_name test-mv.com www.test-mv.com;

            location / {
                    try_files $uri $uri/ =404;
            }
    }