default_sites: |
    server {
            listen 80;
            listen [::]:80;
            location / {
              # This would be the directory where your React app's static files are stored at
              root /var/www/test-mv.com/html;
              index index.html index.htm;
              try_files $uri $uri/ =404;
            }

            location /api {
              client_max_body_size 50M;
              proxy_pass http://localhost:8000;
              proxy_set_header Host $host;
              proxy_set_header X-Real-IP $remote_addr;
              proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
              proxy_set_header X-Forwarded-Proto $scheme;
            }

            location ~* \.com {
              proxy_pass http://localhost:3000;
              proxy_redirect off;
              proxy_http_version 1.1;
              proxy_set_header Upgrade $http_upgrade;
              proxy_set_header Connection "Upgrade";
              proxy_set_header Host $http_host;
              proxy_set_header X-Real-IP $remote_addr;
              proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
              proxy_set_header X-NginX-Proxy true;
            }

            server_name test-mv.com www.test-mv.com;
    }