

---
- name: Deploy React App Front-end Build
  connection: ssh
  hosts: staging_host
  vars:
    homeDir: /home/ubuntu
    repo_folder: /var/www/github-deployment/repos
    live_folder_html: /var/www/test-mv.com/html
    live_folder_api: /var/www/test-mv.com/api
    repo_name: MatthieuVeillon/Fischy
    privateKey: /Users/matt/.ssh/id_rsa
    ansible_distribution_release: "xenial" #trusty
    database_user: fischy
    database_name: fischy
    database_host: localhost
    database_password: fischy
    database_port: 5432
    service_name: fischy-api

# tasks, indented under playbook name
  tasks:
    - name: Create APP Directory
      file:
        path: "{{live_folder_html}}"
        state: directory

    - name: Create API Directory
      file:
        path: "{{live_folder_api}}"
        state: directory

    - name: Install https APT transport
      apt:
        name: apt-transport-https
        update_cache: true

    - name: YARN | Add Yarn APT key
      apt_key:
        url: https://dl.yarnpkg.com/debian/pubkey.gpg
        state: present

    - name: YARN | Add Yarn APT repo
      apt_repository:
        repo: deb https://dl.yarnpkg.com/debian/ stable main
        state: present
        filename: yarn

    - name: NODE | Add Node APT key
      apt_key:
        url: "https://deb.nodesource.com/gpgkey/nodesource.gpg.key"
        state: present

    - name: NODE | Add Node APT repo
      apt_repository:
        repo: "deb https://deb.nodesource.com/node_14.x {{ ansible_distribution_release }} main"
        state: present
        update_cache: yes

    - name: Install Packages
      apt: name={{ item }} update_cache=yes state=latest
      with_items:
        - build-essential
        - nodejs
        - git
        - mcrypt
        - nginx
        - curl
        - yarn

    - name: PM2 | Install
      yarn:
        name: pm2
        global: yes

    - name: Install packages
      apt:
        name:
          - postgresql
          - '{{ (ansible_python_version is version("3.0.0", ">=")) | ternary("python3-psycopg2", "python-psycopg2") }}'
        update_cache: true

# Create User / Group to be used by POSTGRES
    - name: Create fischy group
      group:
        name: "{{database_user}}"
        state: present

    - name: Create fischy user
      user:
        name: "{{database_user}}"
        state: present
        group: "{{database_user}}"

    - name: POSTGRES Create users
      become: true
      become_user: postgres
      postgresql_user:
        name: "{{database_user}}"
        state: present
        password: "{{database_password}}"

    - name: POSTGRES - Create postgresql database
      postgresql_db:
        name: "{{database_name}}"
        state: present
        owner: "{{database_user}}"
      become: true
      become_user: postgres

    - name: Git clone repo
      git:
        repo: git@github.com:{{ repo_name }}.git
        dest: "{{ repo_folder }}"
        force: yes
        update: yes

    - name: APP | Install dependencies
      command: yarn install
      args:
        chdir: "{{ repo_folder }}/app"

    - name: APP | Build project
      command: yarn build
      args:
        chdir: "{{ repo_folder }}/app"
      environment:
        NODE_ENV: production
        REACT_APP_API_URL: http://www.test-mv.com/api/

    - name: APP | Copy build to live directory
      command: cp -TRv dist {{ live_folder_html }}
      args:
        chdir: "{{ repo_folder }}/app"

    - name: API | Install dependencies
      command: yarn install
      args:
        chdir: "{{ repo_folder }}/api"

    - name: API | Build project
      command: yarn build
      args:
        chdir: "{{ repo_folder }}/api"

    - name: API | Copy build to live directory
      command: cp -TRv build {{ live_folder_api }}
      args:
        chdir: "{{ repo_folder }}/api"

    - name: API | Copy node_modules to live directory
      command: cp -R node_modules {{ live_folder_api }}
      args:
        chdir: "{{ repo_folder }}/api"

    - name: API | Copy .sequelizerc to live directory
      command: cp .sequelizerc {{ live_folder_api }}
      args:
        chdir: "{{ repo_folder }}/api"

    - name: Configure .sequelizerc for production
      command: sed -i "s/'src'/''/g" .sequelizerc
      args:
        chdir: "{{ live_folder_api }}"

    - name: API | Stop the service
      command: pm2 stop {{service_name}}
      become: true
      ignore_errors: yes

    - name: API | Delete the service
      command: pm2 delete {{service_name}}
      become: true
      ignore_errors: yes

    - name: API | migrate postgres models
      command: node_modules/.bin/sequelize db:migrate
      args:
        chdir: "{{ live_folder_api }}"
      environment:
        NODE_ENV: production
        DATABASE_HOST: "{{database_host}}"
        DATABASE_NAME: "{{database_name}}"
        DATABASE_USER: "{{database_user}}"
        DATABASE_PASSWORD: "{{database_password}}"
        DATABASE_PORT: "{{database_port}}"

    - name: API | seed postgres
      command: node_modules/.bin/sequelize db:seed:all
      args:
        chdir: "{{ live_folder_api }}"
      environment:
        NODE_ENV: production
        DATABASE_HOST: "{{database_host}}"
        DATABASE_NAME: "{{database_name}}"
        DATABASE_USER: "{{database_user}}"
        DATABASE_PASSWORD: "{{database_password}}"
        DATABASE_PORT: "{{database_port}}"

    - name: API | Start service
      command: pm2 start -u {{database_user}} --hp /home/{{database_user}} --name {{service_name}} server.js -- -NODE_ENV $NODE_ENV -DATABASE_HOST $DATABASE_HOST -DATABASE_NAME $DATABASE_NAME -DATABASE_USER $DATABASE_USER -DATABASE_PASSWORD $DATABASE_PASSWORD -DATABASE_PORT $DATABASE_PORT
      become: true
      args:
        chdir: "{{live_folder_api}}"
      environment:
        NODE_ENV: production
        DATABASE_HOST: "{{database_host}}"
        DATABASE_NAME: "{{database_name}}"
        DATABASE_USER: "{{database_user}}"
        DATABASE_PASSWORD: "{{database_password}}"
        DATABASE_PORT: "{{database_port}}"

    - name: setup Nginx
      include_role:
        name: nginx

# end of Playbook